### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by paigeadelethompson** [alpinelinux/alpine-netboot#1]
why not just take it down?

**Comment by clandmeter** [comment]
Are the links ok now?

**Comment by paigeadelethompson** [comment]
https://github.com/alpinelinux/alpine-netboot/blob/master/alpine-ipxe/x86_64/ipxe.lkrn

**Comment by paigeadelethompson** [comment]
![image](https://user-images.githubusercontent.com/47037454/53855231-97b40800-3f81-11e9-901d-53eea0970546.png)

**Comment by paigeadelethompson** [comment]
but I eventually found what I was looking for on the original site anyway :P

**Comment by MaxPeal** [comment]
@paigeadelethompson have you a link?
